### PR TITLE
Make TODO checker work again

### PR DESCRIPTION
**Pull request by szepeviktor**
Without extended regexp it should be `'\(todo\|fixme\)'`

### CODE REVIEW

**Comment by szepeviktor** [comment]
Actually it could be just `'todo|fixme'`

**Comment by szepeviktor** [comment]
It worked because of `--extended-regexp`

**Comment by szepeviktor** [comment]
#331 all green, todo lives happily ever after :)

**Comment by romm** [comment]
> #331 all green, todo lives happily ever after :)

Indeed! Thanks for noticing.

**Comment by romm** [comment]
Thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
