### PR TITLE
Remove ext-cache from CI

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@romm Seem like ext-cache has zero effectiveness :)

kép

"Setup PHP" finished in 1 second.

**Comment by romm** [comment]
Good idea, that will remove a lot of configuration code. Could you remove it from the other files as well?

**Comment by szepeviktor** [comment]
Done 🍏 

Please squash commits.

**Comment by romm** [comment]
Thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
