### PR TITLE
base namespaces are T_STRING when tokenized

### PR DESCRIPTION
**Pull request by robchett**
Not happy with the fix, it feels wrong, but it does appear to be an issue with PHPs internal TokenParser and not this package

https://3v4l.org/OQ37v

### CODE REVIEW

**Comment by robchett** [comment]
Fixes https://github.com/CuyZ/Valinor/issues/394

**Comment by romm** [comment]
Hi @robchett, thanks for the fix, it looks reasonable to me considering the issue.

Could you please provide a non-regression test for this?

**Comment by robchett** [comment]
99% sure that's not the best way to test this, the specific namespace requirements make it a bit tricky. Happy to revisit if you have a suggestion for a better way to do this.

**Comment by robchett** [comment]
Hi @romm, is anything else needed for this PR?

**Comment by romm** [comment]
Hi @robchett, just changed things a bit but overall everything was fine by me. Thanks for the fix submission!

**Pull request merged**
