### PR TITLE
feat: handle multiline type declaration

### LINKED ISSUE #18: Multiline type declarations seem to confuse the library overall
Take following example:

```php
<?php

namespace My\App;

use CuyZ\Valinor\Attribute\StaticMethodConstructor;
use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\MapperBuilder;

require_once __DIR__ . '/Valinor/vendor/autoload.php';

class MyArrayWrapper
{
    /** @var array{
     *     0: string,
     *     1: int,
     *     2: bool
     * }
     */
    public array $value;
}

$mapper = (new MapperBuilder())
    ->withCacheDir(__DIR__ . '/cache')
    ->mapper();

var_dump($mapper->map(MyArrayWrapper::class, ['value' => [0 => 'a', 1 => '1', 2 => 'true']]));
```

The type parser does not understand how to proceed here:

```
php example.php 

Fatal error: Uncaught CuyZ\Valinor\Type\Types\UnresolvableType: The type `array{` for property `My\App\MyArrayWrapper::$value` could not be resolved: Shaped array must define one or more elements, for instance `array{foo: string}`. in /app/cache/8dc7bc5e71167e9e09fdc3de1db078cad5175923.php:20
Stack trace:
#0 /app/Valinor/src/Cache/Compiled/CompiledPhpFileCache.php(70): CuyZ\Valinor\Cache\Compiled\PhpCacheFile@anonymous->value()
#1 /app/Valinor/src/Cache/ChainCache.php(33): CuyZ\Valinor\Cache\Compiled\CompiledPhpFileCache->get('class-definitio...', NULL)
#2 /app/Valinor/src/Cache/VersionedCache.php(34): CuyZ\Valinor\Cache\ChainCache->get('class-definitio...', NULL)
#3 /app/Valinor/src/Definition/Repository/Cache/CacheClassDefinitionRepository.php(33): CuyZ\Valinor\Cache\VersionedCache->get('class-definitio...')
#4 /app/Valinor/src/Mapper/Tree/Builder/ClassNodeBuilder.php(35): CuyZ\Valinor\Definition\Repository\Cache\CacheClassDefinitionRepository->for(Object(CuyZ\Valinor\Definition\ClassSignature))
#5 /app/Valinor/src/Mapper/Tree/Builder/CasterNodeBuilder.php(35): CuyZ\Valinor\Mapper\Tree\Builder\ClassNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#6 /app/Valinor/src/Mapper/Tree/Builder/VisitorNodeBuilder.php(28): CuyZ\Valinor\Mapper\Tree\Builder\CasterNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#7 /app/Valinor/src/Mapper/Tree/Builder/ValueAlteringNodeBuilder.php(31): CuyZ\Valinor\Mapper\Tree\Builder\VisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#8 /app/Valinor/src/Mapper/Tree/Builder/ShellVisitorNodeBuilder.php(30): CuyZ\Valinor\Mapper\Tree\Builder\ValueAlteringNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#9 /app/Valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(23): CuyZ\Valinor\Mapper\Tree\Builder\ShellVisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#10 /app/Valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(21): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#11 /app/Valinor/src/Mapper/TreeMapperContainer.php(57): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell))
#12 /app/Valinor/src/Mapper/TreeMapperContainer.php(31): CuyZ\Valinor\Mapper\TreeMapperContainer->node('My\\App\\MyArrayW...', Array)
#13 /app/example.php(26): CuyZ\Valinor\Mapper\TreeMapperContainer->map('My\\App\\MyArrayW...', Array)
#14 {main}

Next CuyZ\Valinor\Mapper\Tree\Exception\UnresolvableShellType: The type `array{` for property `My\App\MyArrayWrapper::$value` could not be resolved: Shaped array must define one or more elements, for instance `array{foo: string}`. in /app/Valinor/src/Mapper/Tree/Shell.php:40
Stack trace:
#0 /app/Valinor/src/Mapper/Tree/Shell.php(57): CuyZ\Valinor\Mapper\Tree\Shell->__construct(Object(CuyZ\Valinor\Type\Types\UnresolvableType), Array)
#1 /app/Valinor/src/Mapper/Tree/Builder/ClassNodeBuilder.php(41): CuyZ\Valinor\Mapper\Tree\Shell->child('value', Object(CuyZ\Valinor\Type\Types\UnresolvableType), Array, Object(CuyZ\Valinor\Definition\EmptyAttributes))
#2 /app/Valinor/src/Mapper/Tree/Builder/CasterNodeBuilder.php(35): CuyZ\Valinor\Mapper\Tree\Builder\ClassNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#3 /app/Valinor/src/Mapper/Tree/Builder/VisitorNodeBuilder.php(28): CuyZ\Valinor\Mapper\Tree\Builder\CasterNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#4 /app/Valinor/src/Mapper/Tree/Builder/ValueAlteringNodeBuilder.php(31): CuyZ\Valinor\Mapper\Tree\Builder\VisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#5 /app/Valinor/src/Mapper/Tree/Builder/ShellVisitorNodeBuilder.php(30): CuyZ\Valinor\Mapper\Tree\Builder\ValueAlteringNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#6 /app/Valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(23): CuyZ\Valinor\Mapper\Tree\Builder\ShellVisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#7 /app/Valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(21): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#8 /app/Valinor/src/Mapper/TreeMapperContainer.php(57): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell))
#9 /app/Valinor/src/Mapper/TreeMapperContainer.php(31): CuyZ\Valinor\Mapper\TreeMapperContainer->node('My\\App\\MyArrayW...', Array)
#10 /app/example.php(26): CuyZ\Valinor\Mapper\TreeMapperContainer->map('My\\App\\MyArrayW...', Array)
#11 {main}
  thrown in /app/Valinor/src/Mapper/Tree/Shell.php on line 40
```

Note: this is just #5, but with different formatting.

One of the most complex types from one of customer projects (could be useful for future expansion of type parsing) :

```php
/**
 * @psalm-immutable
 *
 * @psalm-import-type VariantRawArrayType from Variant
 * @psalm-import-type AssortmentRawArrayType from Assortment
 * @psalm-import-type AttachmentRawArrayType from Attachment
 * @psalm-import-type AwardRawArrayType from Award
 * @psalm-import-type BrandRawArrayType from Brand
 * @psalm-import-type PriceRawArrayType from Price
 * @psalm-import-type TaxonomyRawArrayType from Taxonomy
 *
 * @psalm-type ProductRawArrayType = array{
 *    id: non-empty-string,
 *    isActive: bool,
 *    sku: string,
 *    name: string,
 *    description: ?string,
 *    shortDescription: ?string,
 *    synonyms: string,
 *    clientFields: array<non-empty-string, mixed>,
 *    brand: array<non-empty-string, mixed>,
 *    hazardStatements: list<string>,
 *    precautionaryStatements: list<string>,
 *    mainTaxonomy: TaxonomyRawArrayType,
 *    taxonomies: list<TaxonomyRawArrayType>,
 *    taxonomyListingIds: list<non-empty-string>,
 *    attachments: list<AttachmentRawArrayType>,
 *    assortments: list<AssortmentRawArrayType>,
 *    variants: list<VariantRawArrayType>,
 *    mainVariant: VariantRawArrayType,
 *    relatedProductIds: array<string, list<non-empty-string>>,
 *    variationName: ?string,
 *    skuProvidedBySupplier: ?string,
 *    awards?: ?list<AwardRawArrayType>,
 *    created: string,
 *    updated: string,
 *    prices: list<PriceRawArrayType>
 * }
 */
final class Product
{
    // <snip>

    /**
     * @psalm-param array{
     *     _score: float,
     *     _source: ProductRawArrayType
     * } $data
     */
    public static function fromArray(array $data): self
    {
        // <snip>
    }
}
```

### PR DESCRIPTION
**Pull request by romm**
The following type will now be handled:

```php
/**
 * @var array{
 *     foo: string,
 *     bar: int
 * }
 */
public array $foo;
```

Fixes #18

### CODE REVIEW

**Review by babadee08 — APPROVED** [review]

**Review by Ocramius — APPROVED** [review]
Verified the simplistic example of #18 against this, and it seems to work as expected.

Still trying out the complex use-case (with type imports).

**Comment by romm** [comment]
> Still trying out the complex use-case (with type imports).

I guess you're adding the "imported types" manually then? Makes me think that would be an interesting feature to have in the future. 🙂

**Comment by Ocramius** [comment]
I'll report a separate issue about that, mostly for the backlog (perhaps community can contribute): imported types are really something quite advanced.

**Comment by romm** [comment]
I'm merging this; @Ocramius please tell me if you find other issues on more complex type declarations. 😉

**Pull request merged**
